CREATE TABLE TELEFONE (
	ID_CLIENTE INTEGER, 
	DDD_TELEFONE NUMBER(2), 
	NUM_TELEFONE VARCHAR2(10), 
	CONSTRAINT PK_TELEFONE PRIMARY KEY ( ID_CLIENTE, DDD_TELEFONE, NUM_TELEFONE ),
	CONSTRAINT FK_TELEFONE_CLIENTE FOREIGN KEY ( ID_CLIENTE ) REFERENCES CLIENTE
);


DESC ou DESCRIBE - mostra a estrutura da tabela


CREATE TABLE TIPO(
	ID_TIPO NUMBER(2),
	NOM_TIPO VARCHAR2(15),
	CONSTRAINT PK_TIPO PRIMARY KEY(ID_TIPO)
);


CREATE TABLE CONDOMINIO(
	ID_CONDOMINIO NUMBER(3),
	NOM_CONDOMINIO VARCHAR2(30),
	ID_TIPO NUMBER(2),
	CONSTRAINT PK_CONDOMINIO PRIMARY KEY (ID_CONDOMINIO),
	CONSTRAINT FK_CONDOMINIO_TIPO FOREIGN KEY (ID_TIPO) REFERENCES TIPO
);


CREATE TABLE UNIDADE(
	NUM_UNIDADE NUMBER(4),
	ID_CONDOMINIO NUMBER(3),
	NUM_PROPRIETARIO VARCHAR2(40),
	CONSTRAINT PK_UNIDADE PRIMARY KEY (NUM_UNIDADE, ID_CONDOMINIO),
	CONSTRAINT FK_UNIDADE_CONDOMINIO FOREIGN KEY (ID_CONDOMINIO) REFERENCES CONDOMINIO
);
	

CREATE TABLE TAXA(
	NUM_TAXA NUMBER(6),
	NUM_UNIDADE NUMBER(4),
	ID_CONDOMINIO NUMBER(3),
	DTV_TAXA DATE,
	VLR_TAXA NUMBER(7,2),
	CONSTRAINT PK_TAXA PRIMARY KEY (NUM_TAXA),
	CONSTRAINT FK_TAXA_UNIDADE FOREIGN KEY (NUM_UNIDADE, ID_CONDOMINIO) REFERENCES UNIDADE
);